### ISSUE TITLE
error trying the project

### ISSUE THREAD

**Issue by parniantaghipour** [jzhang533/yolov5-flask#1]
Hi,
I try to use this project; but when I upload the photo from my PC, I got the below error.
Did I do anything wrong? I am new.
```
Traceback (most recent call last):
  File "/home/parnian/PycharmProjects/yolo_deploy/venv/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/parnian/PycharmProjects/yolo_deploy/venv/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/parnian/PycharmProjects/yolo_deploy/venv/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/parnian/PycharmProjects/yolo_deploy/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/parnian/PycharmProjects/yolo_deploy/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/parnian/PycharmProjects/yolo_deploy/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/parnian/PycharmProjects/yolo_deploy/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/parnian/PycharmProjects/yolo_deploy/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/parnian/PycharmProjects/yolo_deploy/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/parnian/PycharmProjects/yolo_deploy/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/parnian/PycharmProjects/yolo_deploy/yolov5-flask/app.py", line 41, in predict
    results = get_prediction(img_bytes)
  File "/home/parnian/PycharmProjects/yolo_deploy/yolov5-flask/app.py", line 24, in get_prediction
    results = model(imgs, size=640)  # includes NMS
  File "/home/parnian/PycharmProjects/yolo_deploy/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/parnian/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 260, in forward
    files.append(Path(im.filename).with_suffix('.jpg').name if isinstance(im, Image.Image) else f'image{i}.jpg')
  File "/usr/lib/python3.6/pathlib.py", line 837, in with_suffix
    raise ValueError("%r has an empty name" % (self,))
ValueError: PosixPath('.') has an empty name

```
Thank you very much.

**Comment by jzhang533** [comment]
this is a bug of ultralytics/yolov5, and has been fixed in latest release. 
ultralytics/yolov5#2702

**Comment by kty-lfc** [comment]
Hi  @jzhang533, 
                  I found this error after run your code :
Adding AutoShape...
Traceback (most recent call last):
  File "app.py", line 14, in <module>
    model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True).autoshape()  # for PIL/cv2/np inputs and NMS
  File "D:\Users\XXX\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'AutoShape' object has no attribute 'autoshape'

**Comment by Prakhar0809** [comment]
> Hi @jzhang533, I found this error after run your code : Adding AutoShape... Traceback (most recent call last): File "app.py", line 14, in model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True).autoshape() # for PIL/cv2/np inputs and NMS File "D:\Users\XXX\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1177, in **getattr** raise AttributeError("'{}' object has no attribute '{}'".format( AttributeError: 'AutoShape' object has no attribute 'autoshape'

I'm also facing the same issue, did you happen to find a solution?

**Comment by jzhang533** [comment]
[ultralytics/yolov5](https://github.com/ultralytics/yolov5) has evolved a lot.
I've updated this tiny demo script to make it work again.
